# Generated by Django 3.2.3 on 2021-05-18 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coeff', models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True)),
                ('const', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=10, null=True)),
                ('default_unit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.metric')),
                ('units', models.ManyToManyField(to='db.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.location')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=50)),
                ('datatype', models.CharField(choices=[('PERCENT', '%'), ('RATIO', ':'), ('TOTAL', 'total')], default='TOTAL', max_length=10)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('timescale', models.CharField(blank=True, default='annual', max_length=20)),
                ('forecast', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='db.location')),
                ('metric', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='db.metric')),
                ('source', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.source')),
                ('unit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.unit')),
            ],
            options={
                'ordering': ('location', 'metric', 'start'),
            },
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['location'], name='db_data_locatio_1efdcc_idx'),
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['metric'], name='db_data_metric__8cf1c1_idx'),
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['start'], name='db_data_start_f12eb0_idx'),
        ),
        migrations.AddConstraint(
            model_name='data',
            constraint=models.UniqueConstraint(fields=('metric', 'location', 'timescale', 'start', 'source', 'publication_date'), name='unique-datapoint'),
        ),
    ]
